### PR TITLE
Install bids validator

### PR DESCRIPTION
**Pull request by hkethi002**
BIDS export tries to validate the downloaded bids hierarchy but skips it when it can't find it. This would prevent a lot of 24 hour fmriprep runs that are going to fail.
Should we give a config option to skip bids validation?

Example of logs currently:
`WARNING:utils:Skipping validation, validator is not present `

### CODE REVIEW

**Comment by lmperry** [comment]
Looks good. Has this been tested locally?

**Comment by hkethi002** [comment]
No, I always seem to run into errors whenever I try to build the fmriprep gear, I'm not sure if it's because of some docker environment thing or that I don't allocate enough memory to it. I'll keep looking into it as it does make developing the gear not the fastest.
Also, I realize I have the default set to false instead of true, is there a reason we want it to be true instead of false? Is it possible for fmriprep to succeed if the data is not in a valid bids format?

**Comment by hkethi002** [comment]
After testing it, found out that when downloading a single session, we don't create the dataset_description.json file, which will always cause bids_validation to fail.
- [ ] Use session filter instead of single container download

**Comment by hkethi002** [comment]
After further testing, the "on-the-fly" bids download should create a dataset description, otherwise it will always fail bids validation, (it should check to see if there is one attached to the project, and if not populate it with some project metadata

**Pull request closed without merging**
